import { useState, useEffect } from 'react';
import {
  View, Text, StyleSheet, TouchableOpacity, ScrollView,
  ActivityIndicator, Alert
} from 'react-native';
import * as FileSystem from 'expo-file-system';
import * as Sharing from 'expo-sharing';
import * as DocumentPicker from 'expo-document-picker';
import {
  ArrowLeft, Download, Upload, CheckCircle, Lock, CreditCard, FileText
} from 'lucide-react-native';
import { agreementsAPI, uploadAPI } from '../services/api';
import { generateAgreement } from '../services/groq';
import { colors, spacing, radius, fontSize, shadow } from '../theme';

const AGREEMENT_FEE = 50;
const GATEWAYS = [
  { id: 'telebirr', name: 'Telebirr', color: '#0077B6' },
  { id: 'cbe', name: 'CBE Birr', color: '#1B5E20' },
  { id: 'dashen', name: 'Dashen Bank', color: '#B71C1C' },
];

export default function AgreementScreen({ route, navigation }) {
  const { applicationId } = route.params;
  const [step, setStep] = useState(1);
  const [matchInfo, setMatchInfo] = useState(null);
  const [gateway, setGateway] = useState('');
  const [paying, setPaying] = useState(false);
  const [generating, setGenerating] = useState(false);
  const [agreementText, setAgreementText] = useState('');
  const [uploading, setUploading] = useState(false);
  const [pickedFile, setPickedFile] = useState(null);
  const [loadingInfo, setLoadingInfo] = useState(true);

  useEffect(() => {
    agreementsAPI.get(applicationId)
      .then(({ agreement }) => {
        setMatchInfo(agreement?.applications);
        if (agreement?.paid) setStep(agreement?.status === 'signed' ? 4 : 2);
      })
      .catch(() => {}) // No agreement yet — that's fine, stay on step 1
      .finally(() => setLoadingInfo(false));
  }, [applicationId]);

  const handlePay = async () => {
    if (!gateway) return Alert.alert('Select a payment method');
    setPaying(true);
    try {
      await agreementsAPI.pay(applicationId, gateway);
      setGenerating(true);
      const listing = matchInfo?.listings;
      const seeker = matchInfo?.users;
      try {
        const text = await generateAgreement({
          seekerName: seeker?.name || 'Room Seeker',
          providerName: listing?.users?.name || 'Room Provider',
          roomTitle: listing?.title || 'the room',
          location: listing?.city || 'Ethiopia',
          rent: listing?.price || '—',
          moveIn: 'As agreed',
          leaseDuration: listing?.lease_duration || 'As agreed',
          rules: listing?.house_rules || 'Standard house rules apply',
        });
        setAgreementText(text);
      } catch {
        setAgreementText(fallbackAgreement());
      }
      setGenerating(false);
      setStep(2);
    } catch (err) {
      Alert.alert('Payment failed', err.message);
    } finally {
      setPaying(false);
    }
  };

  const fallbackAgreement = () => `HOUSEMATE AGREEMENT

This agreement formalizes the housemate arrangement between the Room Provider and Room Seeker for the property listed on Debale.

1. RENT & PAYMENT — Monthly rent as agreed, due on the 1st of each month.
2. LEASE DURATION — As specified in the listing.
3. HOUSE RULES — Both parties agree to respect shared space and quiet hours.
4. TERMINATION — 30 days written notice required from either party.
5. SIGNATURES — Room Provider: ___________  Room Seeker: ___________

Generated by Debale Platform · debale.et`;

  const handleDownload = async () => {
    try {
      const fileUri = FileSystem.documentDirectory + 'Debale_Housemate_Agreement.txt';
      await FileSystem.writeAsStringAsync(fileUri, agreementText || fallbackAgreement());
      if (await Sharing.isAvailableAsync()) {
        await Sharing.shareAsync(fileUri);
      } else {
        Alert.alert('Saved', 'Agreement saved to app storage.');
      }
      setTimeout(() => setStep(3), 500);
    } catch (err) {
      Alert.alert('Download failed', err.message);
    }
  };

  const pickSignedFile = async () => {
    const result = await DocumentPicker.getDocumentAsync({ type: ['image/*', 'application/pdf'] });
    if (result.canceled) return;
    setPickedFile(result.assets[0]);
  };

  const handleSubmit = async () => {
    if (!pickedFile) return Alert.alert('Please select your signed agreement first');
    setUploading(true);
    try {
      const { url } = await uploadAPI.photo(
        { uri: pickedFile.uri, mimeType: pickedFile.mimeType, fileName: pickedFile.name },
        'agreements'
      );
      await agreementsAPI.upload(applicationId, url, pickedFile.name);
      setStep(4);
    } catch (err) {
      Alert.alert('Upload failed', err.message);
    } finally {
      setUploading(false);
    }
  };

  if (loadingInfo) return <View style={styles.centered}><ActivityIndicator size="large" color={colors.teal} /></View>;

  return (
    <View style={styles.container}>
      <View style={styles.header}>
        <TouchableOpacity onPress={() => navigation.goBack()} style={styles.backBtn}><ArrowLeft size={20} color={colors.dark} /></TouchableOpacity>
        <Text style={styles.headerTitle}>Housemate Agreement</Text>
      </View>

      {/* Progress */}
      <View style={styles.progressRow}>
        {[1, 2, 3, 4].map(s => (
          <View key={s} style={[styles.progressDot, s <= step && styles.progressDotActive]} />
        ))}
      </View>

      <ScrollView contentContainerStyle={{ padding: spacing.xxl, paddingBottom: 60 }}>
        {/* Step 1: Pay */}
        {step === 1 && (
          <View>
            <View style={styles.lockBanner}>
              <Lock size={20} color={colors.gold} />
              <Text style={styles.lockText}>Pay a one-time fee of <Text style={{ fontWeight: '700' }}>{AGREEMENT_FEE} ETB</Text> to generate and unlock your agreement.</Text>
            </View>

            <Text style={styles.sectionLabel}>Select Payment Method</Text>
            <View style={styles.gatewayGrid}>
              {GATEWAYS.map(g => {
                const active = gateway === g.id;
                return (
                  <TouchableOpacity key={g.id} style={[styles.gatewayCard, active && { borderColor: g.color, backgroundColor: `${g.color}10` }]} onPress={() => setGateway(g.id)}>
                    <View style={[styles.gatewayIcon, { backgroundColor: g.color }]}><Text style={styles.gatewayIconText}>{g.name.slice(0, 3)}</Text></View>
                    <Text style={[styles.gatewayName, active && { color: g.color }]}>{g.name}</Text>
                  </TouchableOpacity>
                );
              })}
            </View>

            <TouchableOpacity style={styles.payBtn} onPress={handlePay} disabled={!gateway || paying || generating}>
              {paying ? <ActivityIndicator color="white" /> : generating
                ? <Text style={styles.payBtnText}>🤖 Generating agreement...</Text>
                : <Text style={styles.payBtnText}>Pay {AGREEMENT_FEE} ETB & Generate</Text>}
            </TouchableOpacity>
          </View>
        )}

        {/* Step 2: Download */}
        {step === 2 && (
          <View>
            <View style={styles.successIconWrap}><CheckCircle size={40} color={colors.green} /></View>
            <Text style={styles.stepTitle}>Agreement Ready!</Text>
            <Text style={styles.stepSub}>Your AI-generated agreement is ready to download.</Text>

            <View style={styles.previewCard}>
              <View style={styles.previewHeader}>
                <FileText size={16} color={colors.teal} />
                <Text style={styles.previewFileName}>Debale_Housemate_Agreement.txt</Text>
              </View>
              <Text style={styles.previewText} numberOfLines={8}>{agreementText || fallbackAgreement()}</Text>
            </View>

            <TouchableOpacity style={styles.payBtn} onPress={handleDownload}>
              <Download size={16} color="white" />
              <Text style={styles.payBtnText}>Download Agreement</Text>
            </TouchableOpacity>
            <TouchableOpacity onPress={() => setStep(3)} style={{ marginTop: spacing.md, alignItems: 'center' }}>
              <Text style={styles.skipLink}>Already downloaded → Go to Upload</Text>
            </TouchableOpacity>
          </View>
        )}

        {/* Step 3: Sign & Upload */}
        {step === 3 && (
          <View>
            <Text style={styles.stepTitle}>Upload Signed Agreement</Text>
            <Text style={styles.stepSub}>Once both parties have signed, upload the signed copy here.</Text>

            <TouchableOpacity style={[styles.uploadBox, pickedFile && styles.uploadBoxFilled]} onPress={pickSignedFile}>
              {pickedFile ? (
                <>
                  <CheckCircle size={32} color={colors.green} />
                  <Text style={[styles.uploadTitle, { color: colors.green }]}>File Ready!</Text>
                  <Text style={styles.uploadSub}>{pickedFile.name}</Text>
                </>
              ) : (
                <>
                  <Upload size={32} color={colors.gray400} />
                  <Text style={styles.uploadTitle}>Tap to select signed file</Text>
                  <Text style={styles.uploadSub}>PDF, JPG or PNG</Text>
                </>
              )}
            </TouchableOpacity>

            <TouchableOpacity style={styles.payBtn} onPress={handleSubmit} disabled={!pickedFile || uploading}>
              {uploading ? <ActivityIndicator color="white" /> : <Text style={styles.payBtnText}>Submit Signed Agreement</Text>}
            </TouchableOpacity>
          </View>
        )}

        {/* Step 4: Complete */}
        {step === 4 && (
          <View style={{ alignItems: 'center', paddingTop: spacing.xxl }}>
            <View style={[styles.successIconWrap, { width: 90, height: 90, borderRadius: 45 }]}>
              <CheckCircle size={48} color={colors.green} />
            </View>
            <Text style={styles.stepTitle}>Agreement Complete! 🎉</Text>
            <Text style={[styles.stepSub, { textAlign: 'center', marginBottom: spacing.xxl }]}>
              Your signed agreement was received. Both parties have been notified.
            </Text>
            <TouchableOpacity style={styles.payBtn} onPress={() => navigation.navigate('DashboardHome')}>
              <Text style={styles.payBtnText}>Back to Dashboard</Text>
            </TouchableOpacity>
          </View>
        )}
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.cream },
  centered: { flex: 1, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.cream },
  header: { flexDirection: 'row', alignItems: 'center', gap: spacing.md, paddingHorizontal: spacing.xxl, paddingTop: 56, paddingBottom: spacing.md },
  backBtn: { width: 36, height: 36, borderRadius: 18, backgroundColor: 'white', alignItems: 'center', justifyContent: 'center', ...shadow.sm },
  headerTitle: { fontSize: fontSize.lg, fontWeight: '700', color: colors.dark },
  progressRow: { flexDirection: 'row', gap: 6, paddingHorizontal: spacing.xxl, marginBottom: spacing.md },
  progressDot: { flex: 1, height: 4, borderRadius: 2, backgroundColor: colors.gray200 },
  progressDotActive: { backgroundColor: colors.teal },
  lockBanner: { flexDirection: 'row', gap: 12, backgroundColor: colors.goldLight, padding: spacing.lg, borderRadius: radius.md, marginBottom: spacing.xl, alignItems: 'flex-start' },
  lockText: { flex: 1, fontSize: fontSize.sm, color: colors.gray700, lineHeight: 19 },
  sectionLabel: { fontSize: fontSize.sm, fontWeight: '600', color: colors.gray700, marginBottom: spacing.md },
  gatewayGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm, marginBottom: spacing.xl },
  gatewayCard: { flexBasis: '47%', flexGrow: 1, flexDirection: 'row', alignItems: 'center', gap: 10, backgroundColor: 'white', borderRadius: radius.md, borderWidth: 2, borderColor: colors.gray200, padding: spacing.md },
  gatewayIcon: { width: 32, height: 32, borderRadius: 8, alignItems: 'center', justifyContent: 'center' },
  gatewayIconText: { color: 'white', fontSize: 9, fontWeight: '700' },
  gatewayName: { fontSize: fontSize.sm, fontWeight: '600', color: colors.dark },
  payBtn: { flexDirection: 'row', gap: 8, backgroundColor: colors.teal, height: 50, borderRadius: radius.md, alignItems: 'center', justifyContent: 'center' },
  payBtnText: { color: 'white', fontWeight: '700', fontSize: fontSize.base },
  successIconWrap: { width: 70, height: 70, borderRadius: 35, backgroundColor: colors.greenLight, alignItems: 'center', justifyContent: 'center', alignSelf: 'center', marginBottom: spacing.lg },
  stepTitle: { fontSize: fontSize.lg, fontWeight: '700', color: colors.dark, textAlign: 'center', marginBottom: 6 },
  stepSub: { fontSize: fontSize.sm, color: colors.gray500, marginBottom: spacing.xl, textAlign: 'center' },
  previewCard: { backgroundColor: 'white', borderRadius: radius.md, borderWidth: 1, borderColor: colors.gray200, marginBottom: spacing.xl, overflow: 'hidden' },
  previewHeader: { flexDirection: 'row', alignItems: 'center', gap: 8, padding: spacing.md, backgroundColor: colors.gray50, borderBottomWidth: 1, borderBottomColor: colors.gray200 },
  previewFileName: { fontSize: fontSize.sm, fontWeight: '600', color: colors.dark },
  previewText: { padding: spacing.md, fontSize: 11, color: colors.gray600, lineHeight: 16, fontFamily: 'monospace' },
  skipLink: { fontSize: fontSize.sm, color: colors.gray400, textDecorationLine: 'underline' },
  uploadBox: { borderWidth: 2, borderColor: colors.gray200, borderStyle: 'dashed', borderRadius: radius.md, alignItems: 'center', justifyContent: 'center', paddingVertical: 40, backgroundColor: colors.gray50, marginBottom: spacing.xl, gap: 6 },
  uploadBoxFilled: { borderColor: colors.green, backgroundColor: colors.greenLight, borderStyle: 'solid' },
  uploadTitle: { fontWeight: '600', fontSize: fontSize.base, color: colors.dark },
  uploadSub: { fontSize: fontSize.xs, color: colors.gray500 },
});
